#! /bin/sh

# reset polybar
$HOME/.config/polybar/launch.sh bspwm

# Autostart
[ ! "$(pidof -x sxhkd)" ] && sxhkd &
[ ! "$(pidof -x picom)" ] && picom &
[ ! "$(pidof -x nm-applet)" ] && nm-applet &

# locker
# [ ! "$(pidof -x xautolock)" ] && xautolock -locker "$HOME/.local/share/scripts/lock.sh" -time 60 -detectsleep -notify 10 &
xset s 300 5
xss-lock -n /usr/bin/xsecurelock/dimmer -l -- xsecurelock

# setup monitor
monitors=$(xrandr -q | grep " connected " | cut -d " " -f1)
monitor_list=$(printf "%s" "$monitors" | tr '\n' ' ')
num_monitors=$(echo "$monitors" | wc -w)
case $num_monitors in
    1)
        bspc monitor -d I II III IV V VI VII VIII IX X ;;
    2)
        primary=$(echo "$monitor_list" | cut -d ' ' -f1)
        secondary=$(echo "$monitor_list" | cut -d ' ' -f2)
        echo "prim: $primary second: $secondary"
        bspc monitor "$primary" -d I II III IV V
        bspc monitor "$secondary" -d VI VII VII IX X
        bspc wm -O "$primary" "$secondary" ;;
    *)
esac

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a scratchpad sticky=on state=floating hidden=on
alacritty --class scratchpad,scratchpad -e ~/.local/bin/scratch &
