#! /bin/sh

# reset polybar
$HOME/.config/polybar/launch.sh &

# Autostart
[[ ! $(pidof -x sxhkd) ]] && sxhkd &
[[ ! $(pidof -x compton) ]] && compton &
[[ ! $(pidof -x nm-applet) ]] && nm-applet &
[[ ! $(pidof -x feh ) ]] && feh --bg-scale "$HOME/.local/share/images/wallpaper.jpg" &

# locker
[[ ! $(pidof -x xautolock) ]] && xautolock -locker "$HOME/.local/share/scripts/lock.sh" -time 60 -detectsleep -notify 10 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a scratchpad sticky=on state=floating hidden=on
alacritty --class scratchpad,scratchpad -e ~/code/dotfiles/bspwm/.bin/scratch &
